"""Create stock prices table

Revision ID: 9e1447f9e416
Revises: 
Create Date: 2026-09-20 13:54:46.518040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1447f9e416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_prices_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_symbol'))

    op.drop_table('stock_prices')
    # ### end Alembic commands ###
